languageCode = 'en-us'
title = 'Weipeng YAO'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
commentoEnable = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "my personal website"
  background_color_class = "bg-black"
  recent_posts_number = 3
  body_classes = "avenir bg-near-white"
  #post_content_classes = ""


[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/yy2zz1"
